version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    container_name: connectfree
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/data/db